services:
  - type: web
    name: unofficial-api
    env: docker
    dockerCommand: ./scripts/start.api.sh
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: unofficial-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: unofficial-db
          property: connectionString
      - fromGroup: prod-env
  
  - type: worker
    name: unofficial-worker
    env: docker
    dockerCommand: ./scripts/start.worker.sh
    envVars: 
      - key: REDIS_URL
        fromService:
          type: redis
          name: unofficial-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: unofficial-db
          property: connectionString
      - fromGroup: prod-env
  
  - type: worker
    name: unofficial-cron
    env: docker
    dockerCommand: ./scripts/start.cron.sh
    envVars: 
      - key: REDIS_URL
        fromService:
          type: redis
          name: unofficial-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: unofficial-db
          property: connectionString
      - fromGroup: prod-env

  - type: redis
    name: unofficial-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lfu

databases:
  - name: unofficial-db
    databaseName: unofficialdb
    user: unofficialuser

envVarGroups:
  - name: prod-env
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_API
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_DEFAULT_EXPIRY_TIME
        sync: false
      - key: JWT_LONG_EXPIRY_TIME
        sync: false
      - key: POLL_INTERVAL
        sync: false
      - key: PUSH_WEBHOOKS_INTERVAL
        sync: false
      - key: CONVOY_API_KEY
        sync: false
      - key: CONVOY_PROJECT_ID
        sync: false
      - key: SENTRY_DSN
        sync: false

