---
:concurrency: 5
development:
  :queues:
    - render_scheduler
    - render_poller
    - notion_poller
    - push_webhooks
    - webhooks_delivery_scheduler
staging:
  :concurrency: 10
  :queues:
    - render_scheduler
    - render_poller
    - notion_poller
    - push_webhooks
    - webhooks_delivery_scheduler
production:
  :concurrency: 10
  :queues:
    - render_scheduler
    - render_poller
    - notion_poller
    - push_webhooks
    - webhooks_delivery_scheduler
